#!/bin/bash


title(){
    
    echo "  __  __         ____        _    __ _ _            "
    echo " |  \/  |_   _  |  _ \  ___ | |_ / _(_) | ___  ___  "
    echo " | |\/| | | | | | | | |/ _ \| __| |_| | |/ _ \/ __| "
    echo " | |  | | |_| | | |_| | (_) | |_|  _| | |  __/\__ \ "
    echo " |_|  |_|\__, | |____/ \___/ \__|_| |_|_|\___||___/ "
    echo "         |___/                                      "
    echo

}

_help(){
  echo "Usage: $0 [options] <action> <module>"
  echo
  echo "   <action> means: What do you want to do? (install or uninstall)"
  echo "   <module> means: The folder to be installed/uninstalled"
  echo 
  echo "   Options:"
  echo "   h      Print this help"
  echo "   v      Enable verbose"
  echo 
  exit 0
}

ACTION=$1
SKIP=0
if [ "$#" -eq "0" ]; then
    _help
elif [ "$1" = "-h" ]; then
    _help
elif [ "$1" = "-v" ]; then
    verbose=1
    touch /tmp/dotfiles_verbose
    ACTION=$2
    SKIP=1
elif [ "$#" -eq "1" ]; then
    echo "Missing parameters"
    _help
fi

if [ "$ACTION" != "install" ]; then
	if [ "$ACTION" != "uninstall" ]; then
    		echo "Unknown action: $ACTION"
		exit 1
	fi
fi

title
sleep 5

. $PWD/__setup/util.sh

if [ ! -f $CMD_FILE ]; then

	read -p "What is your command for install apps (ex: brew install, apt-get install, pacman -Sy, etc): " cmd

	OS=`uname`
	if [ "$OS" == "Linux" ]; then
		export INSTALL_CMD="sudo $cmd"
	else
		export INSTALL_CMD=$cmd
	fi

	echo $INSTALL_CMD > $CMD_FILE &2>/dev/null
fi

# Prepare things
bash $PWD/__setup/pre.sh

installPkg "zsh"

# get the modules to make actions
idx=0
for mod in "$@"
do
    if [ "$idx" -gt "$SKIP" ]; then
        source $PWD/$mod/module.sh
        $ACTION
    fi
    idx+=1
done

if [ -f /tmp/dotfiles_verbose ]; then
    rm /tmp/dotfiles_verbose
fi
