#!/bin/bash


title(){
    
    echo "  __  __         ____        _    __ _ _            "
    echo " |  \/  |_   _  |  _ \  ___ | |_ / _(_) | ___  ___  "
    echo " | |\/| | | | | | | | |/ _ \| __| |_| | |/ _ \/ __| "
    echo " | |  | | |_| | | |_| | (_) | |_|  _| | |  __/\__ \ "
    echo " |_|  |_|\__, | |____/ \___/ \__|_| |_|_|\___||___/ "
    echo "         |___/                                      "
    echo

}

_help(){
  echo "Usage: $0 [options] <action> <module>"
  echo
  echo "   <action> means: What do you want to do? (install or uninstall)"
  echo "   <module> means: The folder to be installed/uninstalled"
  echo 
  echo "   Options:"
  echo "   h      Print this help"
  echo "   v      Enable verbose"
  echo 
  exit 0
}

run(){
    mod=$1
    action=$2
    echo "Module $mod: $action"
    source $PWD/$mod/module.sh
    $action
}

ACTION=$1
SKIP=0
MODULES=$@
if [ "$#" -eq "0" ]; then
    echo "No parameters. Only basic packages will be installed"
elif [ "$1" = "-h" ]; then
    _help
elif [ "$1" = "-v" ]; then
    verbose=1
    touch /tmp/dotfiles_verbose
    ACTION=$2
    SKIP=1
elif [ "$#" -eq "1" ]; then
    echo "Missing parameters"
    _help
fi

if [ "$#" != "0" ] && [ "$ACTION" != "install" ] && [ "$ACTION" != "uninstall" ]; then
    echo "Unknown action: $ACTION"
    exit 1
fi

title
sleep 5

. $PWD/__setup/util.sh

if [ ! -f $CMD_FILE ]; then

	OS_NAME=`cat /etc/issue 2>/dev/null`

	echo "arch" > $CMD_FILE
	
	echo $OS_NAME | tr '[:upper:]' '[:lower:]' | grep ubuntu
	[[ "$?" -eq 0 ]] && echo "ubuntu" > $CMD_FILE

fi

run base install

exit 0

printSubsection "MAKE SOME PREPARATIONS"
#printSubSubsection "these packages needed to be installed, depending on your OS: build-essential zsh python-dev python3-dev x11-xserver-utils"
installPkg stow curl wget cmake

echo $PWD > "$LOC_FILE"
printOK

# installing zsh
#installPkg "zsh"

# installing basic modules
#run base "install"
#run git "install"

# get the modules to make actions
idx=0
for mod in "$@"
do
    if [ "$idx" -gt "$SKIP" ]; then
        run $mod $ACTION
        #source $PWD/$mod/module.sh
        #$ACTION
    fi
    idx+=1
done

if [ -f /tmp/dotfiles_verbose ]; then
    rm /tmp/dotfiles_verbose
fi
