set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim

"
" All plugin list MUST be put between begin() and end() commands
"
call vundle#begin()

" Vundle se auto-gerencia
Plugin 'gmarik/Vundle.vim'                      " Vundle can self-update
Plugin 'ervandew/supertab'                      " Tab completion
Plugin 'nathanaelkane/vim-indent-guides'        " Exibe linhas de identacao
Plugin 'taglist.vim'                            " Source code browser (uses ctags)
Plugin 'kien/ctrlp.vim'                         " A new finder to vim
Plugin 'bling/vim-airline'                      " A minimalist and objective skin to vim status bars
Plugin 'jiangmiao/auto-pairs'                   " Fechador automático de parenteses, caracteres, etc.
Plugin 'editorconfig/editorconfig-vim'          " Plugin para acesso ao EditorConfig e parse .editorconfig files

" Temas
Plugin 'evgenyzinoviev/vim-vendetta'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()
filetype plugin indent on

"
" General Configurations
"
syntax on
"set number
set relativenumber
set backspace=2
set backspace=indent,eol,start
" indentation
"set shiftwidth=6
set autoindent
set smartindent
set cindent

" Allow paste with the mouse when press F5 (in insert mode)
set pastetoggle=<F5>

"
" Color Scheme, identation, etc
"
set t_Co=256
set background=dark

try
  colorscheme vendetta
catch /^Vim\%((\a\+)\)\=:E185/
  " deal with it
endtry

set ts=2 sw=2 et
let g:indent_guides_auto_colors=0
autocmd VimEnter,ColorScheme * :hi IndentGuidesOdd guibg=black ctermbg=235
autocmd VimEnter,ColorScheme * :hi IndentGuidesEven guibg=darkgrey ctermbg=237
let g:indent_guides_start_level=1
let g:indent_guides_guide_size=1
let g:indent_guides_enable_on_vim_startup=1 "enable on startup

" recognize specific files with known language syntax
autocmd BufNewFile,BufRead *.json set ft=javascript
autocmd BufNewFile,BufRead *.wsdl set ft=xml

" Airline
set laststatus=2
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'

let g:airline_symbols = {}
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tagbar#enabled = 1
let g:airline#extensions#tabline#enabled = 1

let g:airline_theme='onedark'

"
" Other shortcuts
"

" SHIFT

"Shift + Left: Avanca para a aba esquerda
map <S-Left> gT
"# Shift + Right: Avanca para a aba direita
map <S-Right> gt

" CONTROL

" Enable tlist (use ctags)
let Tlist_Use_Right_Window = 1
map <C-T> :TlistToggle<CR>

" Enable netrw
map <C-E> :Vexplore<CR>

" Disable the arrow keys 
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

"
" Plugin specific configurations
"

" netrw (vim native file explorer)
let g:netrw_liststyle=3
let g:netrw_browse_split=4
let g:netrw_winsize=25
let g:netrw_altv=1
