#!/bin/bash

## Created By Aditya Shakya
## Edited By Giovane Boaviagem

logout_locker='xset s activate'

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< "> Lock|> Logout|> Reboot|> Shutdown")"
            case "$MENU" in
                *Lock) ${logout_locker} ;;
                #*Logout)  ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
