#!/bin/sh

##
# ctags must be installed!!
##

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
echo "Updating ctags..."
git ls-files | ctags --verbose=yes --tag-relative -L - -f"$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
