OS=`uname`

DOTFILES_LOC=`cat $HOME/.dotfiles-loc`

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

if [ -d "$ZSH" ]; then
    # Set name of the theme to load --- if set to "random", it will
    # load a random theme each time oh-my-zsh is loaded, in which case,
    # to know which specific one was loaded, run: echo $RANDOM_THEME
    # See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
    ZSH_THEME="typewritten"
    #ZSH_TMUX_FIXTERM=true
    #ZSH_TMUX_FIXTERM_WITH_256COLOR="screen-256color"
    # Set list of themes to pick from when loading at random
    # Setting this variable when ZSH_THEME=random will cause zsh to load
    # a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
    # If set to an empty array, this variable will have no effect.
    # ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

    # Uncomment the following line to use case-sensitive completion.
    # CASE_SENSITIVE="true"

    # Uncomment the following line to use hyphen-insensitive completion.
    # Case-sensitive completion must be off. _ and - will be interchangeable.
    # HYPHEN_INSENSITIVE="true"

    # Uncomment the following line to disable bi-weekly auto-update checks.
    # DISABLE_AUTO_UPDATE="true"

    # Uncomment the following line to automatically update without prompting.
    # DISABLE_UPDATE_PROMPT="true"

    # Uncomment the following line to change how often to auto-update (in days).
    # export UPDATE_ZSH_DAYS=13

    # Uncomment the following line if pasting URLs and other text is messed up.
    # DISABLE_MAGIC_FUNCTIONS=true

    # Uncomment the following line to disable colors in ls.
    # DISABLE_LS_COLORS="true"

    # Uncomment the following line to disable auto-setting terminal title.
    # DISABLE_AUTO_TITLE="true"

    # Uncomment the following line to enable command auto-correction.
    # ENABLE_CORRECTION="true"

    # Uncomment the following line to display red dots whilst waiting for completion.
    # COMPLETION_WAITING_DOTS="true"

    # Uncomment the following line if you want to disable marking untracked files
    # under VCS as dirty. This makes repository status check for large repositories
    # much, much faster.
    # DISABLE_UNTRACKED_FILES_DIRTY="true"

    # Uncomment the following line if you want to change the command execution time
    # stamp shown in the history command output.
    # You can set one of the optional three formats:
    # "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
    # or set a custom format using the strftime function format specifications,
    # see 'man strftime' for details.
    # HIST_STAMPS="mm/dd/yyyy"

    # Would you like to use another custom folder than $ZSH/custom?
    # ZSH_CUSTOM=/path/to/new-custom-folder

    # Which plugins would you like to load?
    # Standard plugins can be found in ~/.oh-my-zsh/plugins/*
    # Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
    # Example format: plugins=(rails git textmate ruby lighthouse)
    # Add wisely, as too many plugins slow down shell startup.
    plugins=(git)

    source $ZSH/oh-my-zsh.sh
fi

# History
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh_history

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

##
# ALIASES
##

# General Aliases
alias tmux='tmux -u2'
alias ..='cd ..'
alias tr='mount_tree'
alias la='ls -la'
alias ll='ls -l'
alias clima='curl v2.wttr.in'
alias keygen='ssh-keygen -b 4096 -t rsa'
#alias cleanDocker='docker system prune -a'
#alias cleanContainers='docker container stop $(docker container ls -lq) && docker container rm $(docker container ls -lq)'
#alias cleanImages='docker stop $(docker ps -q) && docker stop $(docker ps -aq)'

# ALIASES per OS
[ -f "$HOME/.aliases" ] && source "$HOME/.aliases" &>/dev/null
[ -r "$HOME/.aliases_per_os" ] && source "$HOME/.aliases_per_os" &>/dev/null

##
# EXPORTS
##

# General exports
export NODE_ENV="development"
export PATH="$HOME/.cargo/bin:$HOME/bin:$PATH"

# EXPORTS per OS
[ -r "$HOME/.exports" ] && source "$HOME/.exports" &>/dev/null

##
# FUNCTIONS
##

# Use lf to switch directories and bind it to ctrl-o
# Source: https://gist.github.com/LukeSmithxyz/e62f26e55ea8b0ed41a65912fbebbe52
lfcd () {
    if [ ! -d "$HOME/bin" ]; then
        mkdir -p $HOME/bin
    fi
    
    if [ ! -f "$HOME/bin/lf" ]; then
        BASEDIR=`pwd`
        cd $HOME/bin
        wget https://github.com/gokcehan/lf/releases/download/r13/lf-linux-amd64.tar.gz
        tar -zxf lf-linux-amd64.tar.gz
        rm lf-linux-amd64.tar.gz
        cd $BASEDIR
    fi

    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s '^o' 'lfcd\n'

# For some themes which cursor is underline, when exit vim the cursor becomes a box. This function
# fix this error
_fix_cursor() {
  echo -ne '\e[3 q'
}
precmd_functions+=(_fix_cursor)

flag_file="/tmp/flag_file"
if [ ! -f $flag_file ]
then
  command -v neofetch >/dev/null 2>&1 && { neofetch; echo ; touch $flag_file ; }
  if [[ "$OS" = "Linux" ]]; then
      redshift-gtk &
  fi
else
  cmatrix -ab
#  if [ -x /usr/games/cowsay -a -x /usr/games/fortune ]; then
#    fortune | cowsay -f $(ls /usr/share/cowsay/cows/ | shuf -n1)
#    cowsay $(fortune)
#  fi

fi

# See wheather once a day
W=/tmp/weather_daily
if [ ! -f $W ]; then
    clima
    touch $W
    # We create a cron job to remove the file daily, at 5AM
    if [[ "$OS" = "Linux" ]]; then
        if [[ $(crontab -l | egrep -v "^(#|$)" | grep -q 'rm /tmp/weather_daily 2>&1'; echo $?) == 1 ]]
        then
            echo $(crontab -l ; echo '0 5/12/17 * * * rm /tmp/weather_daily 2>&1') | crontab -
        fi
    fi
fi

##
# OTHER USEFUL STUFF...
##
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
